# Generated by Django 4.2.15 on 2024-08-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('age_from', models.IntegerField(verbose_name='Минимальный возраст')),
                ('age_to', models.IntegerField(verbose_name='Максимальный возраст')),
            ],
            options={
                'verbose_name': 'Диапазон возраста',
                'verbose_name_plural': 'Диапазоны возраста',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Гендер',
                'verbose_name_plural': 'Гендеры',
            },
        ),
    ]
