# Generated by Django 4.2.15 on 2024-08-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agetype',
            options={'verbose_name': 'Диапазон возраста', 'verbose_name_plural': 'Диапазоны возрастов'},
        ),
    ]
