# Generated by Django 4.2.15 on 2024-08-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер комнаты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_type_rooms', to='hotels.accommodationtype', verbose_name='Тип размещения')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
