# Generated by Django 4.2.15 on 2024-09-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Этаж номера отеля',
                'verbose_name_plural': 'Этажи номеров отеля',
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Цвет')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Статус номера отеля',
                'verbose_name_plural': 'Статусы номеров отелей',
            },
        ),
        migrations.AlterModelOptions(
            name='accommodationtype',
            options={'verbose_name': 'Тип размещения', 'verbose_name_plural': 'Типы размещений'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер отеля', 'verbose_name_plural': 'Номера отеля'},
        ),
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotels.hotelroom', verbose_name='Номер отеля')),
                ('has_airconditioner', models.BooleanField(default=False, verbose_name='Наличие кондиционера')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Наличие телевизора')),
                ('hast_wifi', models.BooleanField(default=False, verbose_name='Наличие Wi-Fi')),
            ],
            options={
                'verbose_name': 'Параметры номера отеля',
                'verbose_name_plural': 'Параметры номеров отеля',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom', verbose_name='Номер отеля')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_rooms_status', to='hotels.roomstatus', verbose_name='Статус номера отеля')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Статус номера отеля',
                'verbose_name_plural': 'Статусы номеров отеля',
            },
        ),
    ]
