# Generated by Django 4.2.15 on 2024-09-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelroom_roomstatus_alter_accommodationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'verbose_name': 'Номер отеля', 'verbose_name_plural': 'Номера отеля'},
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='accommodation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_type_rooms', to='hotels.accommodationtype', verbose_name='Тип размещения'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotels.hotel', verbose_name='Отель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер комнаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom', verbose_name='Этаж номера отеля'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
