# Generated by Django 4.2.15 on 2024-09-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_hast_wifi_roomsettings_has_wifi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
