# Generated by Django 4.2.15 on 2024-09-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_roomstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelroom', verbose_name='Номер отеля'),
        ),
    ]
