# Generated by Django 4.2.15 on 2024-09-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_hotelroomstatus_id_alter_hotelroomstatus_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomSettings',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='hotels.hotelroom', verbose_name='Номер отеля')),
                ('has_airconditioner', models.BooleanField(default=False, verbose_name='Наличие кондиционера')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Наличие телевизора')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Наличие Wi-Fi')),
            ],
            options={
                'verbose_name': 'Параметры номера отеля',
                'verbose_name_plural': 'Параметры номеров отеля',
            },
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='accommodation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotels.accommodationtype', verbose_name='Тип размещения'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room_status', serialize=False, to='hotels.hotelroom', verbose_name='Номер отеля'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_status', to='hotels.roomstatus', verbose_name='Статус номера отеля'),
        ),
        migrations.DeleteModel(
            name='RoomSettings',
        ),
    ]
