# Generated by Django 4.2.15 on 2024-09-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotelroomsettings_alter_hotelroom_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='accommodation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='hotels.accommodationtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='hotels.hotelroom', verbose_name='Номер отеля'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='info_status', to='hotels.roomstatus', verbose_name='Статус номера отеля'),
            preserve_default=False,
        ),
    ]
