# Generated by Django 4.2.15 on 2024-09-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotel_email_hotel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotels.hotel', verbose_name='Отель')),
                ('check_in', models.TimeField(verbose_name='Время заселения')),
                ('check_out', models.TimeField(verbose_name='Время выселения')),
            ],
            options={
                'verbose_name': 'Политика отеля',
                'verbose_name_plural': 'Политики отелей',
            },
        ),
    ]
