# Generated by Django 4.2.15 on 2024-09-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_alter_hotelroom_max_adults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='accommodation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='hotels.accommodationtype', verbose_name='Тип размещения'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Отель'),
        ),
    ]
