# Generated by Django 4.2.15 on 2024-09-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0016_alter_hotelroom_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='hotelroomstatus',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
    ]
