# Generated by Django 4.2.15 on 2024-09-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_alter_hotelroomstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomstatus',
            options={'verbose_name': 'Статус комнаты', 'verbose_name_plural': 'Статусы комнаты'},
        ),
    ]
