# Generated by Django 4.2.15 on 2024-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoomStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Цвет')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Статус бронирования комнаты',
                'verbose_name_plural': 'Статусы бронирований комнат',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Цвет')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Статус бронирования',
                'verbose_name_plural': 'Статусы бронирований',
            },
        ),
    ]
