# Generated by Django 4.2.15 on 2024-09-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0015_alter_hotelroom_max_adults'),
        ('clients', '0003_alter_client_gender'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated at')),
                ('client_name', models.CharField(max_length=64, verbose_name='Имя гостя')),
                ('start_date', models.DateField(verbose_name='Дата заселения')),
                ('end_date', models.DateField(verbose_name='Дата выселения')),
                ('adults', models.IntegerField(verbose_name='Количество взрослых')),
                ('children', models.IntegerField(verbose_name='Количество детей')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='reservations.reservationstatus', verbose_name='Статус')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.reservation', verbose_name='Бронирование')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotelroom', verbose_name='Комната')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='reservations.reservationroomstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронирование комнаты',
                'verbose_name_plural': 'Бронирования комнат',
            },
        ),
        migrations.CreateModel(
            name='ReservationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('is_main_client', models.BooleanField(default=False, verbose_name='Основной клиент')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='clients.client', verbose_name='Клиент')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_client', to='reservations.reservation', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Бронирование клиента',
                'verbose_name_plural': 'Бронирования клиентов',
            },
        ),
    ]
