# Generated by Django 4.2.15 on 2024-09-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_gender'),
        ('reservations', '0003_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='clients.client', verbose_name='Клиент'),
        ),
    ]
