# Generated by Django 4.2.15 on 2024-09-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_alter_hotelroomstatus_created_at_and_more'),
        ('reservations', '0004_alter_reservationclient_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(through='reservations.ReservationRoom', to='hotels.hotelroom'),
        ),
        migrations.AlterField(
            model_name='reservationroom',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='reservations.reservation', verbose_name='Бронирование'),
        ),
    ]
