# Generated by Django 4.2.15 on 2024-09-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_rooms_alter_reservationroom_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
    ]
