# Generated by Django 4.2.15 on 2024-09-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationclient',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='reservations.reservation', verbose_name='Бронирование'),
        ),
    ]
