# Generated by Django 4.2.15 on 2024-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservationclient_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
    ]
